/**:
  ros__parameters:
    robot_description_planning:
      default_velocity_scaling_factor: 1.0
      default_acceleration_scaling_factor: 1.0
      
      joint_limits:
        joint_1:
          has_velocity_limits: true
          max_velocity: 0.8727      # 50 deg/s
          has_acceleration_limits: true
          max_acceleration: 3.0
        joint_2:
          has_velocity_limits: true
          max_velocity: 0.8727
          has_acceleration_limits: true
          max_acceleration: 3.0
        joint_3:
          has_velocity_limits: true
          max_velocity: 0.8727
          has_acceleration_limits: true
          max_acceleration: 3.0
        joint_4:
          has_velocity_limits: true
          max_velocity: 0.8727
          has_acceleration_limits: true
          max_acceleration: 3.0
        joint_5:
          has_velocity_limits: true
          max_velocity: 0.8727
          has_acceleration_limits: true
          max_acceleration: 3.0


# # ROS 2 Parameter File Format
# /**:
#   ros__parameters:
#     robot_description_planning:
#       # Global Scaling Factors
#       default_velocity_scaling_factor: 0.5
#       default_acceleration_scaling_factor: 0.5

#       # Joint Limits
#       # NOTE: We enabled acceleration limits (set to 1.0) because the 
#       # TimeOptimalParameterization adapter REQUIRES them to calculate timestamps.
#       joint_limits:
#         joint_1:
#           has_velocity_limits: true
#           max_velocity: 1.0
#           has_acceleration_limits: true
#           max_acceleration: 1.0
#         joint_2:
#           has_velocity_limits: true
#           max_velocity: 1.0
#           has_acceleration_limits: true
#           max_acceleration: 1.0
#         joint_3:
#           has_velocity_limits: true
#           max_velocity: 1.0
#           has_acceleration_limits: true
#           max_acceleration: 1.0
#         joint_4:
#           has_velocity_limits: true
#           max_velocity: 1.0
#           has_acceleration_limits: true
#           max_acceleration: 1.0
#         joint_5:
#           has_velocity_limits: true
#           max_velocity: 1.0
#           has_acceleration_limits: true
#           max_acceleration: 1.0



