# ROS 2 Parameter File Format
# We map these parameters to the 'robot_description_kinematics' namespace
/**:
  ros__parameters:
    robot_description_kinematics:
      arm_group:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
